export const GAME_TOKENS = {
	BRIEF_REPOSITORY: Symbol("BRIEF_REPOSITORY"),
	CONCEPT_REPOSITORY: Symbol("CONCEPT_REPOSITORY"),
	CONSTRAINT_REPOSITORY: Symbol("CONSTRAINT_REPOSITORY"),
	GAME_REPOSITORY: Symbol("GAME_REPOSITORY"),
	UNEXPECTED_ISSUE_REPOSITORY: Symbol("UNEXPECTED_ISSUE_REPOSITORY"),
	VENUE_REPOSITORY: Symbol("VENUE_REPOSITORY"),
	CATERING_REPOSITORY: Symbol("CATERING_REPOSITORY"),
	ENTERTAINMENT_REPOSITORY: Symbol("ENTERTAINMENT_REPOSITORY"),
};
